export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_EMAIL: '/verify-email',
  RESET_PASSWORD: '/reset-password',
  RESEND_VERIFICATION: '/resend-verification',
  PROFILE: '/profile',
  COACH_APPLY: '/coach/apply',
  ADMIN: '/admin',
  SUBSCRIPTION_PLANS: '/subscription/plans',
  QUESTIONS: '/questions',
  ADD_QUESTION: '/questions/add',
  EDIT_QUESTION: '/questions/edit',
  PENDING_QUESTIONS: '/admin/pending-questions',
  SOLUTION_HISTORY: '/solutions',
  PROGRESS: '/progress',
  FIND_PEER: '/peer-interviews/find',
  PEER_INTERVIEWS: '/peer-interviews',
  PEER_INTERVIEW_SESSION: '/peer-interviews/sessions/:id',
};
